apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    {{- include "webserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webserver.service.type }}
  ports:
    - port: {{ .Values.webserver.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
  {{- include "webserver.selectorLabels" . | nindent 4 }}
